import { Navbar } from "@/components/navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Music Player App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className + " bg-gray-950 text-white"}>
        <Navbar />
        <main className="container m-auto h-[calc(100vh-4rem)] flex items-center justify-center">
          {children}
        </main>
      </body>
    </html>
  );
}
